task 7 initial
ksilex/testguru pull request #9
Opened 2021-01-16 18:36 UTC by ksilex

2021-01-16 19:19 UTC, BubuntuClu requested changes

2021-01-16 19:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :associated_test, only: %i[create new edit update]
edit update зачем для этих методов искать тест?

2021-01-16 19:19 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{user}/#{project}"
возвращай тут сразу хэлпер `link_to`

2021-01-16 19:19 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header
передавай сюда явно объект вопроса и проверяй его состояние, существует ли он в БД

2021-01-16 19:19 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
опцию лучше оставить, она укорачивает некоторые роуты

2021-01-16 19:19 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
опцию лучше оставить, она укорачивает некоторые роуты

2021-01-16 19:29 UTC, ksilex commented on app/controllers/questions_controller.rb
> +  before_action :associated_test, only: %i[create new edit update]
для вывода @test.title

2021-01-16 19:29 UTC, ksilex commented on config/routes.rb
> +    resources :questions
в таком случае в edit нельзя рендерить форму, а создавать отдельный шаблон, потому что в форме требуется @test и @question для роута, с shallow true @test будет nil, поэтому так оставил

2021-01-16 19:29 UTC, ksilex commented on app/helpers/application_helper.rb
> +    "https://github.com/#{user}/#{project}"
не понял

2021-01-16 19:50 UTC, ksilex commented on app/helpers/application_helper.rb
> +    "https://github.com/#{user}/#{project}"
уже понял

2021-01-16 20:48 UTC, ksilex commented on app/controllers/questions_controller.rb
> +  before_action :associated_test, only: %i[create new edit update]
почему то question.test мой мозг полностью игнорировал

2021-01-16 21:03 UTC, ksilex commented on config/routes.rb
> +    resources :questions
и по другому тоже не работает, если оставить только @question, то в форме будет создаваться неправильной роут на создание вопроса

2021-01-16 21:47 UTC, ksilex commented on config/routes.rb
> +    resources :questions
и до этого теперь тоже допер

2021-01-17 16:44 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
правильно, в форме будет ожидаться [@test, @question], для того чтобы создать новый вопрос тебе нужен тест, ты его находишь и подставляются в это выражение обе переменные и получается путь тот, который ведет на роут по созданию вопроса. а для редактирования вопроса, тебе не нужен тест, только сам вопрос. тогда у тебя как ты заметил тест будет nil, а вопрос будет. тогда роут будет просто question_path и будет вести на роут редактирования. это [@test, @question] нужно только для построения роута, из-за наличия переменной будет зависить какой роут сформируется. то что ты сделал в итоге, по сути под капотом и происходит.

2021-01-19 06:47 UTC, merged